apiVersion: v2
name: rocketmq
description: RocketMQ Helm chart
type: application

version: 12.6.0-rc.0
appVersion: '5.4.0'

maintainers:
  - name: itboon
    url: 'https://github.com/itboon/rocketmq-helm'

keywords:
  - rocketmq
  - kubernetes
  - apache